- name: Add the nodesource repo
  yum:
    name: https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodejs-8.10.0-1nodesource.x86_64.rpm
    state: present

- name: Install Node
  yum:
    name: nodejs
    state: present

- name: Add the Yarn repo
  copy:
    src: yarn.repo
    dest: /etc/yum.repos.d/

- name: Install Yarn
  yum:
    name: yarn-1.5.1
    state: present  
