---
- name: Copy the NGINX repository definition
  copy: src=nginx.repo dest=/etc/yum.repos.d/

- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for NGINX
  copy: src=RPM-GPG-KEY-NGINX dest=/etc/pki/rpm-gpg

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg

- name: Add the IUS reository
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present

- name: Install Vim
  yum:
    name: vim
    state: latest
    update_cache: yes

- name: Set SELinux to permissive
  selinux:
    policy: targeted
    state: permissive

- name: Create web directory
  file:
    path: /var/www/public
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0755
    setype: httpd_sys_content_t

- name: Allow ssh login with password
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '#PasswordAuthentication yes'
    line: 'PasswordAuthentication yes'
    state: present
  notify: Restart sshd
